require_relative 'config/environment'
require "sinatra/activerecord/rake"

desc('Loads up a console!')
task :console do
  ActiveRecord::Base.logger = Logger.new(STDOUT)
  Pry.start
end

desc('Tells the world hello')
task :helloworld do
  a = 1
  a + 2
  puts "Hell0 W0rld"
end
